[package]
name = "mem_file"
version = "0.1.0"
authors = ["ElasT0ny <elast0ny00@gmail.com>"]
license = "MIT OR Apache-2.0"

[dependencies]
cfg-if = "0.1"

[target.'cfg(windows)'.dependencies]
winapi = {version = "0.3", features = ["winbase", "handleapi", "fileapi", "memoryapi", "errhandlingapi", "synchapi"]}

[target.'cfg(unix)'.dependencies]
nix = "0.10"
libc = "0.2"
